#!/bin/sh

while true
    # 900 seconds is 15 minuntes
	sleep ${ONLINECHECK_DELAY}
	do

    # web request to google (hopefully they're never down)
    wget -q --tries=10 --timeout=20 -O - https://www.google.co.uk > /dev/null
    if [ $? -eq 0 ]; then
        echo connectivity check: success
    else
        echo connectivity check: failed
        echo restarting ovpn
        sv restart /app/ovpn
    fi
    
done
